config/routes.rb
Rails.application.routes.draw do
  root to: "sites#index"

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :users, only: %i[index show edit update destroy] do
    member do
      get :remove_avatar
      patch :add_admin
      patch :remove_admin
      get :media
      get :followers
      get :following
      post :mark_away
      post :mark_back
    end
    collection do
      get :search
      get :site_admins
    end
  end

  resources :relationships, only: %i[create destroy]

  resources :posts, except: %i[index] do
    resources :comments, except: %i[index show]
    member do
      get :large_image
    end
  end

  resources :events do
    resources :invitations, only: %i[create update]
    resources :comments, except: %i[index show]
    member do
      get :remove_image
    end
    collection do
      get :calendar
    end
  end

  resource :notifications, only: %i[show edit update], path_names: { edit: "settings" } do
    patch :mark_all_as_read
  end

  resources :likes, only: %i[create destroy] do
    collection do
      get :who
    end
  end

  resources :reposts, only: %i[create destroy] do
    collection do
      get :who
      get :select
    end
  end

  resource :timezones, only: %i[edit update]

  resources :bug_reports

  resources :infinite_scroll, only: %i[index]

  get "set_theme", to: "theme#update"

  resources :directs, path: "direct_messages" do
    resources :messages, except: %i[index]
    collection do
      get "user/:user_id", as: :personal, to: "directs#personal"
    end
  end

  get "sitemap.xml", to: "sites#sitemap", format: :xml
  get :privacy_policy, to: "sites#privacy_policy"

  # Push notification subscriptions
  resources :push_subscriptions, only: [ :create ] do
    collection do
      delete :destroy
      get :vapid_public_key
    end
  end

  # PWA files
  get "manifest.json", to: redirect("/manifest.json")
  get "service-worker.js", to: redirect("/service-worker.js")
end

app/controllers/timezones_controller.rb
class TimezonesController < ApplicationController
  before_action :authenticate_user!

  def edit
    set_return_to if params[:return_to]
  end

  def update
    if current_user.update(user_params)
      set_timezone
      redirect_to helpers.safe_return_path, notice: "Timezone updated successfully."
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:timezone)
  end
end

app/views/timezones/_form.html.haml
= form_with model: current_user, url: timezones_path,
data: { controller: "autosubmit-form" } do |f|
  .input-group.mb-3
    = f.label :timezone, "your timezone", 
    class: "input-group-text", for: "time_zone_select"
    = f.time_zone_select :timezone, ActiveSupport::TimeZone.us_zones,
    {}, { class: "form-select", id: "time_zone_select",
    data: {action: "change->autosubmit-form#submitChange"} }
  = f.submit

app/views/timezones/_link_to_form.html.haml
.center
  = link_to edit_timezones_path(return_to: return_to),
  class: 'btn btn-warning' do
    Your Timezone is
    = current_user.timezone

app/views/timezones/edit.html.haml
.row.center-content
  .col-12.col-md-8.mb-3
    %h1 Change your Timezone
    = render 'timezones/form'
    = link_to safe_return_path do
      %i.fa-solid.fa-hand-point-left
      Back