config/routes.rb
Rails.application.routes.draw do
  root to: "sites#index"

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :users, only: %i[index show edit update destroy] do
    member do
      get :remove_avatar
      patch :add_admin
      patch :remove_admin
      get :media
      get :followers
      get :following
      post :mark_away
      post :mark_back
    end
    collection do
      get :search
      get :site_admins
    end
  end

  resources :relationships, only: %i[create destroy]

  resources :posts, except: %i[index] do
    resources :comments, except: %i[index show]
    member do
      get :large_image
    end
  end

  resources :events do
    resources :invitations, only: %i[create update]
    resources :comments, except: %i[index show]
    member do
      get :remove_image
    end
    collection do
      get :calendar
    end
  end

  resource :notifications, only: %i[show edit update], path_names: { edit: "settings" } do
    patch :mark_all_as_read
  end

  resources :likes, only: %i[create destroy] do
    collection do
      get :who
    end
  end

  resources :reposts, only: %i[create destroy] do
    collection do
      get :who
      get :select
    end
  end

  resource :timezones, only: %i[edit update]

  resources :bug_reports

  resources :infinite_scroll, only: %i[index]

  get "set_theme", to: "theme#update"

  resources :directs, path: "direct_messages" do
    resources :messages, except: %i[index]
    collection do
      get "user/:user_id", as: :personal, to: "directs#personal"
    end
  end

  get "sitemap.xml", to: "sites#sitemap", format: :xml
  get :privacy_policy, to: "sites#privacy_policy"

  # Push notification subscriptions
  resources :push_subscriptions, only: [ :create ] do
    collection do
      delete :destroy
      get :vapid_public_key
    end
  end

  # PWA files
  get "manifest.json", to: redirect("/manifest.json")
  get "service-worker.js", to: redirect("/service-worker.js")
end

app/models/message.rb
class Message < ApplicationRecord
  after_commit on: [ :create ] do
    NotifierJob.perform_later(self)
  end

  has_rich_text :body

  belongs_to :direct
  belongs_to :created_by, class_name: "User", foreign_key: "created_by_id"

  has_many :notifications, as: :notifiable, dependent: :destroy

  # validates :body, presence: true

  default_scope { order(created_at: :desc) }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_direct
  before_action :set_message, only: %i[ show edit update destroy ]
  before_action :deny_access!, only: [ :edit, :update, :destroy ],
  unless:  -> { correct_user?(@message.created_by) }

  def show
    # Calls messages/message_frame to include current_user.
    @direct.read_user_notifications(current_user)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("unread_messages_count", partial: "messages/count",
          locals: { user: current_user })
        ]
      end
      format.html
    end
  end

  # GET /messages or /messages.json
  # GET /messages/new
  def new
    @message = @direct.messages.build
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = @direct.messages.build(message_params)
    @message.created_by = current_user

    respond_to do |format|
      if @message.save
        @message.broadcast_prepend_to(@direct, target: "messages", partial: "messages/message_frame",
        locals: { message: @message })
        format.turbo_stream do
          render turbo_stream: [
            # turbo_stream.prepend("messages", partial: "messages/message",
            # locals: { message: @message }),
            turbo_stream.replace("form_message", partial: "messages/form",
            locals: { direct: @direct, message: @direct.messages.build })
          ]
        end
        format.html { redirect_to direct_url(@direct), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @direct }
      else
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("form_message", partial: "messages/form",
            locals: { direct: @direct, message: @message })
          ]
        end
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        @message.broadcast_replace_to(@direct, target: @message, partial: "messages/message_frame",
        locals: { message: @message })
        format.turbo_stream do
          render turbo_stream: [
            # turbo_stream.replace(@message, partial: "messages/message",
            # locals: { message: @message })
          ]
        end
        format.html { redirect_to direct_url(@direct), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @direct }
      else
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(helpers.dom_id(@message, "form"),
            partial: "messages/form",
            locals: { direct: @direct, message: @message })
          ]
        end
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      @message.broadcast_remove_to(@direct, target: @message)
      format.turbo_stream {
        # render turbo_stream: turbo_stream.remove(@message)
      }
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_direct
    @direct = current_user.directs.find_by(id: params[:direct_id])
  end

  def set_message
    @message = @direct.messages.find_by(id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.require(:message).permit(:body)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def current_or_others(user)
    correct_user?(user) ?  "current" : "others"
  end
end

app/views/messages/_count.html.haml
= turbo_frame_tag "unread_messages_count" do
  %span.count= user.notifications.recent_unread_messages_count

app/views/messages/_form.html.haml
= form_with model: [direct, message], id: dom_id(message, "form"), 
data: { controller: "trix-form", 
action: "trix-file-accept->trix-form#checkType trix-change->trix-form#disableSubmit" } do |f|
  = render 'notifications/error_messages', object: f.object

  .field.mb-3
    = f.label :body, class: "form-label"
    = f.rich_text_area :body, class: "form-control"
  .actions.mb-3
    = f.submit class: "btn btn-primary", data: { trix_form_target: "submit" }

app/views/messages/_message.html.haml
- if message.persisted?
  = turbo_frame_tag message, class: "messages" do
    .callout{class: "#{current_or_others(message.created_by)}"}
      - if correct_user?(message.created_by)
        .links-end
          = link_to [:edit, message.direct, message], title: 'Edit' do
            %i.fa-solid.fa-pen-to-square
            Edit
          = link_to [message.direct, message],
          data: { turbo_method: :delete, turbo_confirm: 'Are you sure.' },
          class: 'delete-link', title: 'Delete' do
            %i.fa-solid.fa-trash
      = render 'users/post_user', user: message.created_by
      .content= message.body
      .timestamp
        Posted #{time_ago_in_words(message.created_at)} ago

app/views/messages/_message_frame.html.haml
= turbo_frame_tag message, class: "messages new", src: direct_message_path(message.direct, message)

app/views/messages/edit.html.haml
= turbo_frame_tag @message do
  .modal
    .modal_content
      .row.center-content
        .col-12
          = link_to @direct, class: "close-btn", title: 'Cancel' do
            %i.fa-solid.fa-xmark
          %h1 Editing message

          = render 'form', direct: @direct, message: @message

app/views/messages/new.html.haml
= turbo_frame_tag "new_message" do
  .modal
    .modal_content
      .row.center-content
        .col-12
          = link_to @direct, class: "close-btn", title: 'Cancel' do
            %i.fa-solid.fa-xmark
          %h1 New message

          = render 'form', direct: @direct, message: @message

app/views/messages/show.html.haml
= render @message