config/routes.rb
Rails.application.routes.draw do
  root to: "sites#index"

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :users, only: %i[index show edit update destroy] do
    member do
      get :remove_avatar
      patch :add_admin
      patch :remove_admin
      get :media
      get :followers
      get :following
      post :mark_away
      post :mark_back
    end
    collection do
      get :search
      get :site_admins
    end
  end

  resources :relationships, only: %i[create destroy]

  resources :posts, except: %i[index] do
    resources :comments, except: %i[index show]
    member do
      get :large_image
    end
  end

  resources :events do
    resources :invitations, only: %i[create update]
    resources :comments, except: %i[index show]
    member do
      get :remove_image
    end
    collection do
      get :calendar
    end
  end

  resource :notifications, only: %i[show edit update], path_names: { edit: "settings" } do
    patch :mark_all_as_read
  end

  resources :likes, only: %i[create destroy] do
    collection do
      get :who
    end
  end

  resources :reposts, only: %i[create destroy] do
    collection do
      get :who
      get :select
    end
  end

  resource :timezones, only: %i[edit update]

  resources :bug_reports

  resources :infinite_scroll, only: %i[index]

  get "set_theme", to: "theme#update"

  resources :directs, path: "direct_messages" do
    resources :messages, except: %i[index]
    collection do
      get "user/:user_id", as: :personal, to: "directs#personal"
    end
  end

  get "sitemap.xml", to: "sites#sitemap", format: :xml
  get :privacy_policy, to: "sites#privacy_policy"

  # Push notification subscriptions
  resources :push_subscriptions, only: [ :create ] do
    collection do
      delete :destroy
      get :vapid_public_key
    end
  end

  # PWA files
  get "manifest.json", to: redirect("/manifest.json")
  get "service-worker.js", to: redirect("/service-worker.js")
end

app/models/direct.rb
class Direct < ApplicationRecord
  has_many :conversations, dependent: :destroy
  has_many :users, through: :conversations
  has_many :messages, dependent: :destroy

  validate :user_selected

  include ReadNotifications
  # def read_user_notifications(current_user)
  #   self.notifications.by_unread.where(recipient: current_user).
  #   update_all(is_read: true)
  #   read_comment_notifications(current_user) if self.try(:comments)
  #   read_like_notifications(current_user) if self.try(:likes)
  # end

  def unread_messages_count(current_user)
    current_user.notifications.where(
      notifiable: messages,
      is_read: false
    ).count
  end

private

  def user_selected
    errors.add(:base, "Search and select a user to message.") unless users.length > 0
  end
end

app/controllers/directs_controller.rb
class DirectsController < ApplicationController
  before_action :authenticate_user!
  include InfiniteScroll
  before_action :set_direct, only: %i[ edit update destroy ]
  before_action :set_as_read!, only: [ :show ]

  # GET /directs or /directs.json
  def index
    @directs = current_user.directs
  end

  # GET /directs/1 or /directs/1.json
  def show
    # @direct set in InfiniteScroll.rb.
    @messages = @scrolled_objects # Returned objects in batches of 10.
    @message = @direct.messages.build
  end

  # GET /directs/new
  def new
    @direct = current_user.directs.build
  end

  # GET /directs/1/edit
  def edit
  end

  # POST /directs or /directs.json
  def create
    user = User.search_by(params[:search]).first unless params[:search].blank?
    @direct =
      if user
        current_user.find_or_init_direct_message(user, direct_params)
      else
        current_user.directs.build(direct_params)
      end

    respond_to do |format|
      if @direct.save
        format.turbo_stream do
          flash[:notice] = "Direct message was successfully created."
          render turbo_stream: turbo_stream.action(:redirect, direct_url(@direct))
        end
        #   render turbo_stream: [
        #     turbo_stream.prepend("directs", partial: "directs/direct",
        #     locals: { direct: @direct }),
        #     turbo_stream.replace("new_direct", partial: "directs/new_direct_link")
        #   ]
        # end
        format.html { redirect_to direct_url(@direct), notice: "Direct message was successfully created." }
        format.json { render :show, status: :created, location: @direct }
      else
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("form_direct", partial: "directs/form",
            locals: { direct: @direct })
          ]
        end
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @direct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directs/1 or /directs/1.json
  def update
    user = User.search_by(params[:search]).first
    @direct.users << user if user && !@direct.users.include?(user)

    respond_to do |format|
      if @direct.update(direct_params)
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(@direct, partial: "directs/direct",
            locals: { direct: @direct })
          ]
        end
        format.html { redirect_to direct_url(@direct), notice: "Direct message was successfully updated." }
        format.json { render :show, status: :ok, location: @direct }
      else
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(helpers.dom_id(@direct, "form"),
            partial: "directs/form", locals: { direct: @direct })
          ]
        end
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @direct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directs/1 or /directs/1.json
  def destroy
    @direct.destroy
    @from_show = params[:from_show]

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to directs_url, notice: "Direct message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def personal
    user = User.find_by(id: params[:user_id])
    if user
      direct = current_user.find_or_init_direct_message(user, nil)
      direct.save if direct.new_record?
      redirect_to direct
    else
      redirect_to root
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_direct
    @direct = current_user.directs.find_by(id: params[:id])
    redirect_to directs_path unless @direct
  end

  # Only allow a list of trusted parameters through.
  def direct_params
    params.require(:direct).permit(:name)
  end
end

app/helpers/directs_helper.rb
module DirectsHelper
end

app/views/directs/_direct.html.haml
= turbo_frame_tag direct, class: "direct" do
  .links-end
    = link_to edit_direct_path(direct) do
      %i.fa-solid.fa-pen-to-square
    = button_to direct_path(direct, from_show: from_show ||= nil), method: :delete,
    data: { turbo_confirm: 'Are you sure?' }, 
    class: 'delete-link', title: 'Delete' do
      %i.fa-solid.fa-trash
  - if direct.name
    %h3= direct.name
  .inline
    - if from_show.nil?
      = link_to direct_path(direct, anchor: "footer"), class: "btn btn-primary", 
      data: { turbo: false } do
        %i.fa-solid.fa-envelope
        Message
        - if direct.unread_messages_count(current_user) > 0
          \-
          = direct.unread_messages_count(current_user)
          unread
    - direct.users.all_but_current(current_user).each do |user|
      = render 'users/post_user', user: user

app/views/directs/_form.html.haml
= form_with model: direct, id: dom_id(direct, "form") do |f|
  = render 'notifications/error_messages', object: f.object
  .row
    .col-12.col-md-6
      .field.mb-3
        = f.label :search, class: "form-label"
        .ui-widget
          .input-group
            %span.input-group-text
              %i.fa-solid.fa-magnifying-glass
            = text_field_tag :search, params[:search], id: 'search',
            class: 'form-control',
            data: { controller: "search-box", autocomplete_source: search_users_path }
    .col-12.col-md-6
      .field.mb-3
        = f.label :name, class: "form-label"
        = f.text_field :name, class: "form-control"
  .actions
    = f.submit class: "btn btn-primary"

app/views/directs/_new_direct_link.html.haml
= turbo_frame_tag "new_direct" do
  = link_to new_direct_path do
    %i.fa-solid.fa-envelope
    New Direct Message

app/views/directs/destroy.turbo_stream.haml
- if @from_show == "true"
  - flash[:notice] = "Direct message was successfully destroyed."
  = turbo_stream.action :redirect, directs_url
- else
  = turbo_stream.remove @direct

app/views/directs/edit.html.haml
= turbo_frame_tag @direct, class: "directs" do
  .modal
    .modal_content
      .row.center-content
        .col-12
          = link_to directs_path, class: "close-btn", title: 'Close' do
            %i.fa-solid.fa-xmark
          %h1 Editing Direct Message
          .inline.mb-3
            %b DM With:
            - @direct.users.all_but_current(current_user).each do |user|
              = render 'users/post_user', user: user

          = render 'form', direct: @direct

app/views/directs/index.html.haml
.callout
  .row
    .col-12.col-md-6
      %h1 Direct Messages
    .col-12.col-md-6
      .links-end-md.mb-3= render "directs/new_direct_link"
  = turbo_frame_tag "directs" do
    = render @directs

app/views/directs/new.html.haml
= turbo_frame_tag "new_direct" do
  .modal
    .modal_content
      .row.center-content
        .col-12
          = link_to directs_path, class: "close-btn", title: 'Close' do
            %i.fa-solid.fa-xmark
          %h1 New Direct Message

          = render 'form', direct: @direct

app/views/directs/show.html.haml
= turbo_stream_from @direct
.callout
  = render @direct, from_show: true

.mb-3
  = link_to directs_path do
    %i.fa-solid.fa-hand-point-left
    Back

%h1 Messages
.message-box
  = turbo_frame_tag "messages", data: { controller: "media" } do
    = render @messages
  -# Infinite scroll comments with turbo.
  = render "infinite_scroll/load_more"
  -# New messages will push older messages up
  .anchor

= render "messages/form", direct: @direct, message: @message

.mb-3
  = link_to directs_path do
    %i.fa-solid.fa-hand-point-left
    Back
    