config/routes.rb
Rails.application.routes.draw do
  root to: "sites#index"

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :users, only: %i[index show edit update destroy] do
    member do
      get :remove_avatar
      patch :add_admin
      patch :remove_admin
      get :media
      get :followers
      get :following
      post :mark_away
      post :mark_back
    end
    collection do
      get :search
      get :site_admins
    end
  end

  resources :relationships, only: %i[create destroy]

  resources :posts, except: %i[index] do
    resources :comments, except: %i[index show]
    member do
      get :large_image
    end
  end

  resources :events do
    resources :invitations, only: %i[create update]
    resources :comments, except: %i[index show]
    member do
      get :remove_image
    end
    collection do
      get :calendar
    end
  end

  resource :notifications, only: %i[show edit update], path_names: { edit: "settings" } do
    patch :mark_all_as_read
  end

  resources :likes, only: %i[create destroy] do
    collection do
      get :who
    end
  end

  resources :reposts, only: %i[create destroy] do
    collection do
      get :who
      get :select
    end
  end

  resource :timezones, only: %i[edit update]

  resources :bug_reports

  resources :infinite_scroll, only: %i[index]

  get "set_theme", to: "theme#update"

  resources :directs, path: "direct_messages" do
    resources :messages, except: %i[index]
    collection do
      get "user/:user_id", as: :personal, to: "directs#personal"
    end
  end

  get "sitemap.xml", to: "sites#sitemap", format: :xml
  get :privacy_policy, to: "sites#privacy_policy"

  # Push notification subscriptions
  resources :push_subscriptions, only: [ :create ] do
    collection do
      delete :destroy
      get :vapid_public_key
    end
  end

  # PWA files
  get "manifest.json", to: redirect("/manifest.json")
  get "service-worker.js", to: redirect("/service-worker.js")
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User", foreign_key: "recipient_id"
  belongs_to :notifier, class_name: "User", foreign_key: "notifier_id"
  belongs_to :notifiable, polymorphic: true

  default_scope  { order(created_at: :desc) }
  scope :by_unread, -> { where(is_read: false) }
  scope :by_type, ->(type) { where(notifiable_type: type) }
  scope :by_older_than_month, -> { where("created_at < :date", date: (DateTime.current - 1.month)) }

  def self.recent
    time_range = (Time.current - 1.week)..Time.current
    where(created_at: time_range)
  end

  def self.earlier
    time_range = (Time.current - 2.months)..(Time.current - 1.week)
    where(created_at: time_range)
  end

  def self.recent_unread_count
    recent.by_unread.count
  end

  def self.bell_message_types
    [ "Post", "Comment", "Relationship", "Like", "Event" ]
  end

  def self.bell_messages
    by_type(bell_message_types)
  end

  def self.recent_unread_bell_messages_count
    recent.by_unread.bell_messages.count
  end

  def self.recent_unread_messages_count
    recent.by_unread.by_type("Message").count
  end

  def self.has_recent_unread?
    recent_unread_count != 0
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def show
    @recent_notifications = current_user.notifications.bell_messages.recent
    @earlier_notifications = current_user.notifications.bell_messages.earlier
  end

  def edit
    @receive_mail = current_user.receive_mail || current_user.create_receive_mail
    @receive_push = current_user.receive_push || current_user.create_receive_push
  end

  def update
    @receive_mail = current_user.receive_mail
    @receive_push = current_user.receive_push

    respond_to do |format|
      # Determine which form was submitted and update accordingly
      if params[:receive_mail].present?
        if @receive_mail.update(receive_mail_params)
          format.html {
            redirect_to edit_notifications_path,
            notice: "Email notification settings were successfully updated."
          }
          format.json { render :show, status: :ok, location: @receive_mail }
        else
          format.html { render :edit }
          format.json { render json: @receive_mail.errors, status: :unprocessable_entity }
        end
      elsif params[:receive_push].present?
        if @receive_push.update(receive_push_params)
          format.html {
            redirect_to edit_notifications_path,
            notice: "Push notification settings were successfully updated."
          }
          format.json { render :show, status: :ok, location: @receive_push }
        else
          format.html { render :edit }
          format.json { render json: @receive_push.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to edit_notifications_path, alert: "No settings to update." }
        format.json { head :bad_request }
      end
    end
  end

  def mark_all_as_read
    current_user.notifications.where(is_read: false).
    update_all(is_read: true)
    respond_to do |format|
      format.html {
        redirect_to root_path,
        notice: "ALL Notification were marked as read."
      }
    end
  end

private

  def receive_mail_params
    params.require(:receive_mail).permit(:for_new_posts,
      :for_new_events, :for_new_comments, :for_new_relationships,
      :for_new_likes, :for_new_messages, :send_after_amount, :send_after_unit)
  end

  def receive_push_params
    params.require(:receive_push).permit(:for_new_posts,
      :for_new_events, :for_new_comments, :for_new_relationships,
      :for_new_likes, :for_new_messages, :send_after_amount, :send_after_unit)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def set_as_read!
    notifiable = self.controller_name.classify.constantize.find_by(id: params[:id])
    notifiable.read_user_notifications(current_user)
  end

  def path_to_notifiable(notifiable, anchor = nil)
    case notifiable.class.name
    when "Post"
      post_url(notifiable, anchor: anchor)
    when "Event"
      event_url(notifiable, anchor: anchor)
    when "Relationship"
      user_url(notifiable.user, relationship_id: notifiable.id)
    when "Message"
      direct_url(notifiable.direct, anchor: "message_#{notifiable.id}")
    when "Like"
      path_to_notifiable(notifiable.likeable)
    when "Comment"
      path_to_notifiable(notifiable.commentable, "comment_#{notifiable.id}")
    else root_url
    end
  end
end

app/views/notifications/_count.html.haml
= turbo_frame_tag "recent_unread_count" do
  %span.count= user.notifications.recent_unread_bell_messages_count
  

app/views/notifications/_error_messages.html.haml
- if object.errors.any?
  #error_messages.hide_on_print
    .row
      .col-12
        .alert.alert-danger.alert-dismissible{role: "alert"}
          %h2
            Form contains #{pluralize(object.errors.count, 'error')}
          %ul
            - object.errors.full_messages.each do |msg|
              %li= msg
          %button.btn-close{aria: {label: 'Close'}, data: {bs_dismiss: "alert"}}

app/views/notifications/_flash_messages.html.haml
.hide_on_print
  - if flash[:alert]
    .row
      .col-12
        .alert.alert-danger.alert-dismissible.fade.show{role: "alert"}
          = sanitize(flash[:alert])
          %button.btn-close{aria: {label: 'Close'}, data: {bs_dismiss: "alert"}}

  - if flash[:notice]
    .row
      .col-12
        .alert.alert-primary.alert-dismissible.fade.show{role: "alert"}
          = sanitize(flash[:notice])
          %button.btn-close{aria: {label: 'Close'}, data: {bs_dismiss: "alert"}}

app/views/notifications/_new.turbo_stream.haml
- if notification.notifiable_type == "Message"
  = turbo_stream.replace "unread_messages_count" do
    = render "messages/count", user: user

- elsif Notification.bell_message_types.include?(notification.notifiable_type)
  = turbo_stream.replace "recent_unread_count" do
    = render "notifications/count", user: user

  = turbo_stream.prepend "unread_notifications_list" do
    = render notification
  

app/views/notifications/_notification.html.haml
= turbo_frame_tag notification do
  .p-2.notification{class: "is_read_#{notification.is_read}"}
    = link_to path_to_notifiable(notification.notifiable), 
    class: "post_user", data: { turbo: false } do
      - if notification.notifier.avatar.attached?
        = image_tag thumb_image(notification.notifier.avatar)
      - else
        = image_tag "default_avatar.png"
      = notification.notifier.username
      = notification.action
      .timestamp
        #{time_ago_in_words(notification.created_at)} ago

app/views/notifications/edit.html.haml
- provide :title, 'Notification settings'

.row.center-content
  .col-12.col-lg-10
    %h1 Notification settings

    .mb-3
      %em
        %b How email notifications work
        %ul
          %li 
            Be careful with these settings, email is the only means of notifying 
            you of new activity when not online. 
          %li 
            You will not receive any email notifications while your 
            status is online.
          %li 
            You will receive 1 email notification when all your notifications 
            are marked as read and your status is offline.
          %li 
            If you have unread notification messages, 
            you will not receive another email until your
            [Send after] setting, times out.

    = form_with model: @receive_mail, url: notifications_path, 
    data: { turbo: false } do |f|
      = render 'notifications/error_messages', object: f.object
      
      .feild.mb-3
        .mb-1 
          How often would you like to receive an email notification even if 
          you have unread notification messages?
          %br/
          %em Be careful, if set too high, you might be missing out.
        .row
          .col-12.col-lg-6
            .input-group
              = f.label :send_after_amount, "Send after", class: "input-group-text"
              = f.number_field :send_after_amount, class: "form-control"
              = f.select :send_after_unit, 
              options_for_select([["Minute(s)", "minutes"], ["Hour(s)", "hours"], ["Day(s)", "days"]], 
              f.object.send_after_unit), {}, class: "form-select"
      .mb-1 Receive email notifications when users you follow:
      .feild.mb-1
        = f.check_box :for_new_posts, id: 'cb_posts'
        = f.label :for_new_posts, 'create a new Post', for: 'cb_posts'
      .feild.mb-1
        = f.check_box :for_new_events, id: 'cb_events'
        = f.label :for_new_events, 'create a new Event', for: 'cb_events'
      .feild.mb-1
        = f.check_box :for_new_comments, id: 'cb_comments'
        = f.label :for_new_comments,
        'Comment on something you have posted or commented on', for: 'cb_comments'
      .feild.mb-1
        = f.check_box :for_new_relationships, id: 'cb_relationships'
        = f.label :for_new_relationships, 'start Following you', for: 'cb_relationships'
      .feild.mb-1
        = f.check_box :for_new_likes, id: 'cb_likes'
        = f.label :for_new_likes, 'Likes your content', for: 'cb_likes'
      .feild.mb-3
        = f.check_box :for_new_messages, id: 'cb_messages'
        = f.label :for_new_likes, 'Direct Messages you', for: 'cb_messages'
      .actions.mb-3
        = f.submit 'Update Notification settings', class: 'btn btn-primary'
    
    %hr.my-4
    
    %h2 Push Notifications
    
    .mb-3
      %em
        %b How push notifications work
        %ul
          %li
            Push notifications alert you of new activity even when your browser is closed
            or the app is not open.
          %li
            You will only receive push notifications when you are offline.
            While online, you'll see real-time notifications in the app.
          %li
            %strong Desktop (Chrome, Firefox, Edge, Safari):
            Works immediately after enabling - notifications arrive even when browser is closed.
          %li
            %strong Android:
            Works in Chrome and most browsers - notifications arrive even when browser is closed.
          %li
            %strong iOS (iPhone/iPad):
            Requires Safari and iOS 16.4+. You must add Bullhorn to your home screen 
            (tap Share → Add to Home Screen) for notifications to work when Safari is closed.

    = render "push_subscriptions/enable_button"
    
    .alert.alert-info.mb-3
      %i.fa-solid.fa-info-circle.me-2
      %strong Automatic Email Backup:
      If your push subscription expires (which can happen due to browser updates or security policies),
      we'll automatically send you email notifications to ensure you don't miss anything. 
      When you return to the site, push notifications will be automatically restored.
      
    %em
      .mb-3
        %strong Note:
        Feel free to uncheck all email notification options if you prefer to rely solely on push notifications.

    
    = form_with model: @receive_push, url: notifications_path, 
    data: { turbo: false } do |f|
      = render 'notifications/error_messages', object: f.object
      
      .feild.mb-3
        .mb-1 
          How often would you like to receive push notifications even if 
          you have unread notification messages?
          %br/
          %em Set to 0 minutes to receive every push notification immediately.
        .row
          .col-12.col-lg-6
            .input-group
              = f.label :send_after_amount, "Send after", class: "input-group-text"
              = f.number_field :send_after_amount, class: "form-control"
              = f.select :send_after_unit, 
              options_for_select([["Minute(s)", "minutes"], ["Hour(s)", "hours"], ["Day(s)", "days"]], 
              f.object.send_after_unit), {}, class: "form-select"
      .mb-1 Receive push notifications when users you follow:
      .feild.mb-1
        = f.check_box :for_new_posts, id: 'cb_push_posts'
        = f.label :for_new_posts, 'create a new Post', for: 'cb_push_posts'
      .feild.mb-1
        = f.check_box :for_new_events, id: 'cb_push_events'
        = f.label :for_new_events, 'create a new Event', for: 'cb_push_events'
      .feild.mb-1
        = f.check_box :for_new_comments, id: 'cb_push_comments'
        = f.label :for_new_comments,
        'Comment on something you have posted or commented on', for: 'cb_push_comments'
      .feild.mb-1
        = f.check_box :for_new_relationships, id: 'cb_push_relationships'
        = f.label :for_new_relationships, 'start Following you', for: 'cb_push_relationships'
      .feild.mb-1
        = f.check_box :for_new_likes, id: 'cb_push_likes'
        = f.label :for_new_likes, 'Likes your content', for: 'cb_push_likes'
      .feild.mb-3
        = f.check_box :for_new_messages, id: 'cb_push_messages'
        = f.label :for_new_messages, 'Direct Messages you', for: 'cb_push_messages'
      .actions.mb-3
        = f.submit 'Update Push Notification settings', class: 'btn btn-primary'

app/views/notifications/show.html.haml
.row.center-content
  .col-12.col-md-8
    #notifications{ data: { controller: "push-notification-status" } }
      .mb-3.d-flex.flex-wrap.gap-3
        = button_to 'mark ALL as read', mark_all_as_read_notifications_path,
        title: 'mark ALL notifications as read', class: 'btn btn-primary', 
        method: :patch, data: { turbo: false }
        = link_to edit_notifications_path,
        title: 'Notification Settings', class: 'btn btn-primary' do
          %i.fa-solid.fa-gear
          Settings
        = link_to edit_notifications_path(anchor: "push-notification"), 
        class: "btn btn-success d-none", id: "setup-push-notifications-button" do
          %i.fa-solid.fa-bell
          Setup Push Notifications
      .notifications-box.d-flex.flex-column.mb-3
        %h2 Notifications
        - if @recent_notifications.any?
          %h6.list NEW
          = turbo_frame_tag "unread_notifications_list" do
            = render @recent_notifications
        - if @earlier_notifications.any?
          %h6.list EARLIER
          #unread_notifications_list
            = render @earlier_notifications